### ISSUE TITLE
The selected workspace is flaky

### ISSUE THREAD

**Issue by meierjan** [code-linhao/dotfiles#1]
Hey @code-linhao, 

thanks for sharing your dots. 

I set everything up as you documented, but it turns out the work-space selection is flaky. Sometimes the selection of the workspace before keeps being selected after switching, and sometimes no workspace is selected after switching. However, it works most of the time.

Does this sound familiar?

**Comment by code-linhao** [comment]
Hey, I have also noticed this. I am suspecting this behaviour is due to timing between switching spaces and updating the bar. I'll rework the scripts to resolve this issue when time allows me to!

**Comment by meierjan** [comment]
Wow, thanks for the quick response :) Looking forward!

**Comment by code-linhao** [comment]
Try giving the reworked workspace.sh script and updated sketchybarrc file a try. I've also updated the sketchybarrc file to use font smoothing and changed font weights so keep this in mind.

**Comment by meierjan** [comment]
Hey @code-linhao, thank you, it's A LOT better!
