### ISSUE TITLE
The icons for Time & Date are broken

### ISSUE THREAD

**Issue by meierjan** [code-linhao/dotfiles#2]
Hey, not sure where this is coming from, but the time & date icon can't be displayed. However, I installed the font according to your documentation. I also tried to replace the char with the one from GitHub directly. 
 
Do you have any hint what this can be caused by? I am a noob with this icon fonts. 

One thing I noticed though is that the application icons &  the music-icon are working.

![image](https://user-images.githubusercontent.com/3726563/212742648-872465f7-562e-4a3e-9b77-01b07b9ebc8a.png)

**Comment by code-linhao** [comment]
The time and date icons are using the icons found in a Nerd Font. I have installed and configured it on my system and on SketchyBar to use the JetBrains Mono Nerd Font. I believe the font you are using is not a Nerd Font and hence the icon is not shown.

You can find a list of available Nerd Fonts here:

[nerdfonts.com](https://www.nerdfonts.com/font-downloads)

**Comment by meierjan** [comment]
Thank you! That's solved it <3
